"""Lateral thinking: random word provocation corpus and methodology."""

# Concrete nouns selected for rich associative potential.
# De Bono's rule: always use nouns — they have richer associations than
# verbs or adjectives. Words should be concrete, everyday objects.
RANDOM_WORDS = [
    # Nature
    "tree",
    "river",
    "mountain",
    "cloud",
    "stone",
    "seed",
    "leaf",
    "root",
    "wave",
    "flame",
    "ice",
    "sand",
    "coral",
    "mushroom",
    "vine",
    "fossil",
    "nest",
    "shell",
    "feather",
    "bone",
    "moss",
    "thorn",
    "pollen",
    "cave",
    # Animals
    "spider",
    "whale",
    "ant",
    "eagle",
    "snake",
    "octopus",
    "bee",
    "wolf",
    "turtle",
    "butterfly",
    "shark",
    "crow",
    "frog",
    "elephant",
    "owl",
    "fox",
    # Objects
    "mirror",
    "ladder",
    "knife",
    "clock",
    "bridge",
    "wheel",
    "rope",
    "key",
    "candle",
    "bell",
    "chain",
    "lens",
    "needle",
    "drum",
    "anchor",
    "spring",
    "sponge",
    "funnel",
    "magnet",
    "prism",
    "cage",
    "mask",
    "sail",
    "hinge",
    # Human-made
    "wall",
    "door",
    "window",
    "pipe",
    "tower",
    "fence",
    "tunnel",
    "dam",
    "switch",
    "valve",
    "gear",
    "net",
    "trap",
    "oven",
    "loom",
    "anvil",
    # Food / Materials
    "soap",
    "bread",
    "cheese",
    "honey",
    "clay",
    "glass",
    "rubber",
    "silk",
    "paper",
    "wax",
    "ink",
    "oil",
    "salt",
    "sugar",
    "charcoal",
    "copper",
    # Abstract-ish but concrete
    "shadow",
    "echo",
    "bubble",
    "spark",
    "knot",
    "crack",
    "loop",
    "spiral",
    "layer",
    "edge",
    "gap",
    "pulse",
    "ripple",
    "fog",
    "dust",
    "ash",
    # Tools / Instruments
    "hammer",
    "scissors",
    "brush",
    "compass",
    "telescope",
    "scale",
    "lever",
    "chisel",
    "rake",
    "plow",
    "axe",
    "bolt",
    "clamp",
    "pulley",
    "wedge",
    # Containers
    "bottle",
    "basket",
    "bucket",
    "envelope",
    "box",
    "jar",
    "vault",
    "pocket",
    # Misc
    "tattoo",
    "parachute",
    "domino",
    "kaleidoscope",
    "lighthouse",
    "zipper",
    "trampoline",
    "pendulum",
    "mosaic",
    "origami",
    "labyrinth",
    "hourglass",
    "scarecrow",
    "hammock",
    "catapult",
    "periscope",
    "stethoscope",
    "sundial",
]

# Movement techniques for connecting random word to problem (de Bono)
MOVEMENT_TECHNIQUES = [
    {
        "name": "Extract a principle",
        "instruction": "Take a functional principle of the word and apply it to the problem.",
        "example": "Word 'soap' → principle: something that dissolves after use → idea: a digital ticket that deletes itself after serving its purpose.",
    },
    {
        "name": "Focus on the difference",
        "instruction": "Contrast the random word with the problem. What's different? Use that gap creatively.",
        "example": "Word 'soap' is slippery; banks are static → idea: create a 'fast-track' mobile line that lets customers slide in and out.",
    },
    {
        "name": "Moment to moment",
        "instruction": "Imagine the random word in action, step by step. See what ideas each moment triggers.",
        "example": "Using soap creates bubbles → idea: give waiting customers 'information bubbles' on screens.",
    },
    {
        "name": "Find analogies",
        "instruction": "What is the random word analogous to in the problem domain?",
        "example": "Word 'bridge' connects two sides → what two things in your problem need connecting?",
    },
    {
        "name": "Random associations chain",
        "instruction": "List 5 associations of the word, then connect each to the problem.",
        "example": "Word 'spider' → web, patience, trap, silk, corners → each sparks a different angle on the problem.",
    },
]
