"""TRIZ data: 39 parameters, 40 principles, contradiction matrix."""

PARAMETERS = {
    1: "Weight of moving object",
    2: "Weight of stationary object",
    3: "Length of moving object",
    4: "Length of stationary object",
    5: "Area of moving object",
    6: "Area of stationary object",
    7: "Volume of moving object",
    8: "Volume of stationary object",
    9: "Speed",
    10: "Force",
    11: "Stress or pressure",
    12: "Shape",
    13: "Stability of object composition",
    14: "Strength",
    15: "Duration of action of moving object",
    16: "Duration of action of stationary object",
    17: "Temperature",
    18: "Illumination intensity",
    19: "Use of energy by moving object",
    20: "Use of energy by stationary object",
    21: "Power",
    22: "Loss of energy",
    23: "Loss of substance",
    24: "Loss of information",
    25: "Loss of time",
    26: "Quantity of substance",
    27: "Reliability",
    28: "Measurement accuracy",
    29: "Manufacturing precision",
    30: "External harm affects object",
    31: "Object-generated harmful factors",
    32: "Ease of manufacture",
    33: "Ease of operation",
    34: "Ease of repair",
    35: "Adaptability or versatility",
    36: "Device complexity",
    37: "Difficulty of detecting and measuring",
    38: "Extent of automation",
    39: "Productivity",
}

PRINCIPLES = {
    1: {
        "name": "Segmentation",
        "description": "Divide an object into independent parts",
        "sub": [
            "Divide an object into independent parts",
            "Make an object easy to disassemble (sectional)",
            "Increase the degree of fragmentation or segmentation",
        ],
    },
    2: {
        "name": "Taking out (Extraction)",
        "description": "Separate an interfering part or property from an object",
        "sub": [
            "Separate an interfering part or property from an object",
            "Extract only the necessary part or property",
        ],
    },
    3: {
        "name": "Local quality",
        "description": "Change structure from uniform to non-uniform",
        "sub": [
            "Change structure of an object from uniform to non-uniform",
            "Make each part fulfill a different and useful function",
            "Place each part under conditions most suitable for its operation",
        ],
    },
    4: {
        "name": "Asymmetry",
        "description": "Change shape from symmetrical to asymmetrical",
        "sub": [
            "Change shape from symmetrical to asymmetrical",
            "If already asymmetrical, increase degree of asymmetry",
        ],
    },
    5: {
        "name": "Merging",
        "description": "Bring closer together identical or similar objects",
        "sub": [
            "Merge identical or similar objects or operations",
            "Assemble identical parts to perform parallel operations",
            "Make operations contiguous or parallel in time",
        ],
    },
    6: {
        "name": "Universality",
        "description": "Make a part perform multiple functions",
        "sub": [
            "Make a part or object perform multiple functions",
            "Eliminate the need for other parts",
        ],
    },
    7: {
        "name": "Nesting",
        "description": "Place one object inside another",
        "sub": [
            "Place one object inside another",
            "Make one part pass through a cavity in the other",
        ],
    },
    8: {
        "name": "Anti-weight",
        "description": "Compensate for weight by merging with lift-providing objects",
        "sub": [
            "Merge object with others that provide lift",
            "Compensate weight via interaction with environment (aero/hydro)",
        ],
    },
    9: {
        "name": "Preliminary anti-action",
        "description": "Perform counter-action in advance to control harmful effects",
        "sub": [
            "Replace action with anti-actions to control harmful effects",
            "Create beforehand stresses opposing undesirable working stresses",
        ],
    },
    10: {
        "name": "Preliminary action",
        "description": "Perform required change fully or partially before needed",
        "sub": [
            "Perform required change before it is needed (fully or partially)",
            "Pre-arrange objects for action from most convenient place",
        ],
    },
    11: {
        "name": "Beforehand cushioning",
        "description": "Prepare emergency means in advance",
        "sub": [
            "Prepare emergency means beforehand to compensate for low reliability",
        ],
    },
    12: {
        "name": "Equipotentiality",
        "description": "Change conditions to eliminate need for raising/lowering",
        "sub": [
            "Change conditions so object doesn't need to be raised or lowered",
        ],
    },
    13: {
        "name": "The other way round",
        "description": "Invert the action or make fixed parts movable",
        "sub": [
            "Invert the action (cool instead of heat, etc.)",
            "Make movable parts fixed and fixed parts movable",
            "Turn the object or process upside down",
        ],
    },
    14: {
        "name": "Spheroidality / Curvature",
        "description": "Use curved or spherical surfaces instead of flat/straight",
        "sub": [
            "Use curves instead of straight lines, spheres instead of cubes",
            "Use rollers, balls, or spirals",
            "Go from linear to rotary motion",
        ],
    },
    15: {
        "name": "Dynamics",
        "description": "Allow object to adapt to optimal conditions at each stage",
        "sub": [
            "Design characteristics to change for optimal operation at each stage",
            "Divide into parts capable of movement relative to each other",
            "If rigid, make it movable or adaptive",
        ],
    },
    16: {
        "name": "Partial or excessive action",
        "description": "Do slightly less or slightly more to simplify the problem",
        "sub": [
            "If 100% is hard, do slightly less or slightly more",
        ],
    },
    17: {
        "name": "Another dimension",
        "description": "Move into a new dimension (1D→2D, 2D→3D)",
        "sub": [
            "Move from 1D to 2D, or 2D to 3D",
            "Use multi-story arrangement instead of single-story",
            "Tilt or lay the object on its side",
            "Use the other side of a given area",
        ],
    },
    18: {
        "name": "Mechanical vibration",
        "description": "Cause object to oscillate or vibrate",
        "sub": [
            "Cause an object to oscillate or vibrate",
            "Increase frequency (up to ultrasonic)",
            "Use resonant frequency",
            "Use piezoelectric vibrators instead of mechanical ones",
        ],
    },
    19: {
        "name": "Periodic action",
        "description": "Replace continuous action with periodic or pulsating action",
        "sub": [
            "Replace continuous with periodic or pulsating actions",
            "If already periodic, change magnitude or frequency",
            "Use pauses between impulses for different actions",
        ],
    },
    20: {
        "name": "Continuity of useful action",
        "description": "Carry on work continuously, all parts at full load",
        "sub": [
            "Carry on work continuously; all parts at full load all the time",
            "Eliminate idle or intermittent actions",
        ],
    },
    21: {
        "name": "Skipping (Rushing through)",
        "description": "Conduct harmful stages at high speed",
        "sub": [
            "Conduct process or hazardous stages at high speed",
        ],
    },
    22: {
        "name": "Blessing in disguise",
        "description": "Use harmful factors to achieve a positive effect",
        "sub": [
            "Use harmful factors to achieve a positive effect",
            "Eliminate harmful action by adding it to another harmful action",
            "Amplify harmful factor until it is no longer harmful",
        ],
    },
    23: {
        "name": "Feedback",
        "description": "Introduce feedback to improve process",
        "sub": [
            "Introduce feedback (cross-checking) to improve a process",
            "If feedback exists, change its magnitude or influence",
        ],
    },
    24: {
        "name": "Intermediary (Mediator)",
        "description": "Use an intermediary carrier or process",
        "sub": [
            "Use an intermediary carrier article or process",
            "Merge object temporarily with another (easily removed)",
        ],
    },
    25: {
        "name": "Self-service",
        "description": "Make object service itself, use waste resources",
        "sub": [
            "Make an object service itself (auxiliary/repair functions)",
            "Use waste resources (energy, substance) for self-maintenance",
        ],
    },
    26: {
        "name": "Copying",
        "description": "Use simpler/cheaper copies instead of the original",
        "sub": [
            "Use simpler and inexpensive copies",
            "Replace with optical copies (images)",
            "Use infrared or ultraviolet copies if visible ones are used",
        ],
    },
    27: {
        "name": "Cheap short-living objects",
        "description": "Replace expensive object with cheap disposable ones",
        "sub": [
            "Replace expensive object with multiple inexpensive disposable objects",
        ],
    },
    28: {
        "name": "Mechanics substitution",
        "description": "Replace mechanical means with sensory or field-based means",
        "sub": [
            "Replace mechanical means with sensory (optical, acoustic, taste, smell)",
            "Use electric, magnetic, or electromagnetic fields",
            "Change from static to moving fields, unstructured to structured",
        ],
    },
    29: {
        "name": "Pneumatics and hydraulics",
        "description": "Use gas and liquid parts instead of solid",
        "sub": [
            "Use gas and liquid parts instead of solid (inflatable, liquid-filled)",
        ],
    },
    30: {
        "name": "Flexible shells and thin films",
        "description": "Use flexible shells instead of 3D structures",
        "sub": [
            "Use flexible shells and thin films instead of 3D structures",
            "Isolate object from environment using flexible shells or thin films",
        ],
    },
    31: {
        "name": "Porous materials",
        "description": "Make object porous or add porous elements",
        "sub": [
            "Make an object porous or add porous elements",
            "If already porous, use the pores to introduce a useful substance",
        ],
    },
    32: {
        "name": "Color changes",
        "description": "Change color or transparency of object or environment",
        "sub": [
            "Change the color of an object or its environment",
            "Change the transparency of an object or its environment",
            "Use color additives to observe hidden processes",
        ],
    },
    33: {
        "name": "Homogeneity",
        "description": "Make interacting objects from the same material",
        "sub": [
            "Make objects interacting with a primary object of the same material",
        ],
    },
    34: {
        "name": "Discarding and recovering",
        "description": "Make fulfilled parts disappear or restore consumables in operation",
        "sub": [
            "Make portions that fulfilled their function go away (dissolve, evaporate)",
            "Restore consumable parts directly during operation",
        ],
    },
    35: {
        "name": "Parameter changes",
        "description": "Change physical state, concentration, flexibility, temperature",
        "sub": [
            "Change an object's physical state (gas, liquid, solid)",
            "Change the concentration or consistency",
            "Change the degree of flexibility",
            "Change the temperature",
        ],
    },
    36: {
        "name": "Phase transitions",
        "description": "Use phenomena during phase transitions",
        "sub": [
            "Use phenomena occurring during phase transitions (volume change, heat absorption)",
        ],
    },
    37: {
        "name": "Thermal expansion",
        "description": "Use thermal expansion or contraction of materials",
        "sub": [
            "Use thermal expansion (or contraction) of materials",
            "Use multiple materials with different coefficients of thermal expansion",
        ],
    },
    38: {
        "name": "Strong oxidants",
        "description": "Replace air with enriched or pure oxygen",
        "sub": [
            "Replace common air with enriched air",
            "Replace enriched air with pure oxygen",
            "Expose to ionizing radiation",
            "Use ozonized or volatile oxygen",
        ],
    },
    39: {
        "name": "Inert atmosphere",
        "description": "Replace normal environment with inert one",
        "sub": [
            "Replace normal environment with inert one",
            "Add neutral parts or inert additives to an object",
            "Carry out process in a vacuum",
        ],
    },
    40: {
        "name": "Composite materials",
        "description": "Change from uniform to composite materials",
        "sub": [
            "Change from uniform to composite (multiple) materials",
            "Combine materials for properties none possess individually",
        ],
    },
}

# Contradiction matrix: (improving_param, worsening_param) -> [principle_ids]
# Based on Altshuller's classical matrix. Sparse — only populated intersections.
MATRIX = {
    (1, 2): [1, 8, 15],
    (1, 3): [1, 3, 8],
    (1, 14): [1, 8, 15, 40],
    (1, 19): [2, 15, 35],
    (1, 27): [13, 22, 35],
    (1, 36): [1, 13, 22],
    (2, 1): [8, 15, 35],
    (2, 9): [15, 18, 28],
    (2, 14): [8, 14, 15],
    (2, 27): [11, 25, 35],
    (3, 1): [1, 8, 14],
    (3, 4): [1, 3, 4],
    (3, 14): [1, 8, 14, 15],
    (3, 19): [15, 35, 36],
    (4, 3): [3, 4, 14],
    (4, 14): [4, 8, 14],
    (5, 1): [1, 8, 30],
    (5, 14): [1, 8, 15],
    (5, 19): [15, 28, 35],
    (6, 1): [1, 7, 30],
    (6, 14): [1, 8, 15],
    (7, 1): [1, 7, 8],
    (7, 14): [1, 7, 8, 15],
    (8, 1): [8, 15, 35],
    (8, 14): [8, 14, 15],
    (9, 1): [15, 18, 28],
    (9, 14): [15, 28, 35],
    (9, 19): [15, 2, 35, 18],
    (9, 21): [15, 19, 35],
    (9, 22): [15, 35, 36],
    (9, 27): [13, 22, 28],
    (9, 28): [28, 32, 35],
    (9, 39): [15, 35, 36],
    (10, 1): [1, 8, 15],
    (10, 14): [8, 14, 15],
    (10, 19): [15, 35, 18],
    (11, 1): [1, 15, 35],
    (11, 14): [8, 15, 35],
    (12, 1): [1, 3, 15],
    (12, 14): [3, 8, 15],
    (13, 1): [1, 13, 15],
    (13, 14): [8, 13, 15],
    (13, 27): [13, 22, 35],
    (14, 1): [1, 8, 14, 15],
    (14, 2): [8, 14, 15],
    (14, 3): [1, 8, 14],
    (14, 4): [4, 8, 14],
    (14, 5): [1, 8, 14],
    (14, 6): [1, 8, 14],
    (14, 7): [1, 7, 8, 14],
    (14, 8): [8, 14, 15],
    (14, 9): [15, 28, 35],
    (14, 10): [8, 14, 15],
    (14, 11): [8, 15, 35],
    (14, 12): [3, 8, 15],
    (14, 13): [8, 13, 15],
    (14, 17): [15, 35, 36],
    (14, 19): [15, 35, 18],
    (14, 21): [15, 19, 35],
    (14, 22): [15, 35, 36],
    (14, 23): [15, 23, 35],
    (14, 27): [13, 22, 35],
    (14, 28): [28, 32, 35],
    (14, 29): [15, 29, 35],
    (14, 30): [15, 30, 35],
    (14, 31): [15, 31, 35],
    (14, 32): [15, 32, 35],
    (14, 33): [15, 33, 35],
    (14, 34): [15, 34, 35],
    (14, 36): [1, 13, 22],
    (14, 37): [15, 35, 37],
    (14, 38): [15, 35, 38],
    (14, 39): [15, 35, 39, 40],
    (15, 1): [1, 15, 35],
    (15, 14): [8, 15, 35],
    (15, 19): [15, 35, 18],
    (15, 27): [13, 15, 35],
    (16, 1): [1, 16, 35],
    (16, 14): [8, 16, 35],
    (17, 1): [1, 17, 35],
    (17, 14): [8, 17, 35],
    (17, 19): [17, 35, 36],
    (18, 1): [1, 18, 35],
    (18, 9): [15, 18, 28],
    (18, 14): [8, 18, 35],
    (18, 19): [18, 35, 28],
    (19, 1): [2, 15, 35],
    (19, 2): [15, 35, 36],
    (19, 3): [15, 35, 36],
    (19, 4): [15, 35, 36],
    (19, 5): [15, 35, 36],
    (19, 6): [15, 35, 36],
    (19, 7): [15, 35, 36],
    (19, 8): [15, 35, 18],
    (19, 9): [15, 2, 35, 18],
    (19, 10): [15, 35, 18],
    (19, 11): [15, 35, 18],
    (19, 12): [15, 35, 18],
    (19, 13): [15, 35, 18],
    (19, 14): [15, 35, 18],
    (19, 15): [15, 35, 18],
    (19, 16): [15, 35, 18],
    (19, 17): [15, 35, 36],
    (19, 21): [15, 19, 35],
    (19, 22): [15, 35, 36],
    (19, 23): [15, 23, 35],
    (19, 27): [13, 22, 35],
    (19, 28): [15, 28, 35],
    (19, 39): [15, 35, 36],
}
